name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - "jobboard-backend/**"

  pull_request:
    branches:
      - main
    paths:
      - "jobboard-backend/**"

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: jobboard-backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Check Build
        run: npm install